### ISSUE TITLE
[BUG] 紫卡分析时识别词条错误

### ISSUE THREAD

**Issue by handouy** [KingPrimes/NyxBot#16]
### 问题描述
*简要描述您碰到的问题。*
 在分析某些紫卡时出现报错
### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Windows]
 - JDK信息： [e.g.：17]
 - 版本信息：[e.g.：1.0.5-beta]

### 重现步骤
*如何操作可以重现该问题：*
 发送以下图片时出现错误
![1c40adf7a3257d8a61872ec155b8e64a](https://github.com/KingPrimes/NyxBot/assets/130530218/def101b7-6598-4814-8a62-d7a01cf03392)

### 期待的正确结果
*对您期望发生的结果进行清晰简洁的描述。*
 正常识别紫卡并给出分析结果

### 相关日志输出
*请复制并粘贴任何相关的日志输出。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by KingPrimes** [comment]
已修复
