### ISSUE TITLE
[BUG]“裂缝”和“钢铁裂隙”功能时好时坏

### ISSUE THREAD

**Issue by AwerMing** [KingPrimes/NyxBot#18]
### 问题描述
*简要描述您碰到的问题。*

### 环境信息
*请填写以下信息：*

 - OS信息：  win11
 - JDK信息： 17
 - 版本信息：1.0.6

[XNI0-1 task-5 - 22056] com.nyx.bot.utils.HtmlToImage
: Cannot invoke "java.net.U
ERROR 2024-04-26 12:32:45
RLConnection.getInputStream()" because "this. conn" is null
ERROR 2024-04-26 12:32:45 [XNI0-1 I/0-3- 22056] c.m.s.adapter.WebSocketServerHandler
： Action failed：文件异常，
大小为0ERROR 2024-04-26 12:32:49 [XNI0-1 task-5- 22056] com.nyx.bot.utils.HtmlToImage
: Cannot invoke "java.net.U
：Action failed：文件异常，
RLConnection.getInputStream()" because "this. _conn" is nullERROR 2024-04-26 12:32:49 [XNI0-1 I/0-3 - 22056] c.m.s.adapter.WebSocketServerHandler大小为0
: Cannot invoke "java.net.U
ERROR 2024-04-26 12:34:52 [XNI0-1 task-5 - 22056] com.nyx.bot.utils.HtmlToImage
RLConnection.getInputStream()" because "this._conn" is null
： Action failed：文件异常，
ERROR 2024-04-26 12:34:52 [XNI0-1 I/0-3- 22056] c.m.s.adapter.WebSocketServerHandler
大小为0

<img width="867" alt="Image_1714115363514" src="https://github.com/KingPrimes/NyxBot/assets/67190264/6c674561-5989-4ec0-949a-7d23e25543be">

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by KingPrimes** [comment]
此错误是缺失文件造成的，已修复。请重启应用程序更新最新的资源文件
