### ISSUE TITLE
[功能要求]-查看当前警报

### ISSUE THREAD

**Issue by DAYYYYa** [KingPrimes/NyxBot#40]
### 请描述您的需求或者改进建议
*查看当前警报。*

### 请描述你建议的实现方案
*通过接口获取当前警报内容。*

### 描述您考虑过的替代方案
*修复wiki功能（）。*

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

**Comment by KingPrimes** [comment]
已添加
