### ISSUE TITLE
HTTPUTILS超时时间设置过短。

### ISSUE THREAD

**Issue by AsQuantum** [KingPrimes/NyxBot#42]
### 使用的JDK版本？

OpenJDK-17

### 使用的什么系统？Windows？Linux？macOS？

Windows

### NyxBot 使用的那个版本？

v0.1.2 & main-2024/11/30

### 使用的什么OneBot客户端？ LLOneBot? NapCat?

LLOneBot

### 使用的什么OneBot协议？ OneBot-v11? OneBot-v12?

OneBot-V11

### 使用的什么命令发生了错误？

ALL

### 请详细描述你遇到的bug，包括：

根据命令行报错提示：
```
HttpUtils: timeout
TaskWarframeStatus: 获取数据失败！
```
在此文件中：
https://github.com/KingPrimes/NyxBot/blob/main/src/main/java/com/nyx/bot/utils/http/HttpUtils.java
```
            //调用超时
            .callTimeout(30, TimeUnit.SECONDS)
            //链接超时
            .connectTimeout(30, TimeUnit.SECONDS)
            //读取超时
            .readTimeout(30, TimeUnit.SECONDS) 
```

设置超时时间过短，导致：
![image](https://github.com/user-attachments/assets/c8973b8d-4fdb-4f89-8f1b-3d01a75cdab2)

经过测试调成60秒重新编译后可以正常运行。

**Comment by AsQuantum** [comment]
> Hello! Thank you for filing an issue.
> 
> If this is a bug report, please include relevant logs to help us debug the problem.

[2024-11-30-0-error - 副本.log](https://github.com/user-attachments/files/17964555/2024-11-30-0-error.-.log)

**Comment by KingPrimes** [comment]
30秒应该不短了吧

**Comment by KingPrimes** [comment]
应该是你的网络环境有问题，你尝试请求一下这个地址 https://api.warframestat.us/pc 查看能否访问

**Comment by AsQuantum** [comment]
> 应该是你的网络环境有问题，你尝试请求一下这个地址 https://api.warframestat.us/pc 查看能否访问

是可以访问的（30秒内能加载出来）但是在程序上可能超过30秒处理，这里是我测试的结果：
![image](https://github.com/user-attachments/assets/f3ce52ef-381e-4dfa-965e-e0141521751d)

**Comment by AsQuantum** [comment]
> > 应该是你的网络环境有问题，你尝试请求一下这个地址 https://api.warframestat.us/pc 查看能否访问
> 
> edge浏览器上是可以立即访问的（30秒内能加载出来）但是在程序上可能超过30秒处理，这里是我测试的结果： ![image](https://private-user-images.githubusercontent.com/100147969/391262002-f3ce52ef-381e-4dfa-965e-e0141521751d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5ODk4NjYsIm5iZiI6MTczMjk4OTU2NiwicGF0aCI6Ii8xMDAxNDc5NjkvMzkxMjYyMDAyLWYzY2U1MmVmLTM4MWUtNGRmYS05NjVlLWUwMTQxNTIxNzUxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxNzU5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWYxYjdjYzc4NzRlMzI5MDFjOGE3MmU2NGE4N2YwOWM2OTM0NDQ4ZmM3YTRiZGY2ZDQ3YTAwNDQ0ZDgzNjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OYYnQnVZctmab_Sa9qlWp7A6mCzhEjnES18TBcLV7jM)

如果将上面的client字段改为如下则可以会减少响应时间。（来源于chatgpt)：
![image](https://github.com/user-attachments/assets/0afcbc57-f0e7-43d6-9d3c-817557bf82a9)

**Comment by KingPrimes** [comment]
请使用Okhttp3中的Response.receivedResponseAtMillis() - Response.sentRequestAtMillis()来获取具体的网络相应时间
![image](https://github.com/user-attachments/assets/a09cd245-ca5f-445a-a40e-4f44bfb9d195)
![image](https://github.com/user-attachments/assets/91af728d-90c1-4916-a503-27ab02a5441b)
![image](https://github.com/user-attachments/assets/9628f331-33f0-452f-8634-a1a94a2916a9)

**Comment by KingPrimes** [comment]
并确保你的okhttp3的版本为 4.12.0

**Comment by AsQuantum** [comment]
> 请使用Okhttp3中的Response.receivedResponseAtMillis() - Response.sentRequestAtMillis()来获取具体的网络响应时间，并确保你的okhttp3的版本为 4.12.0 ![image](https://private-user-images.githubusercontent.com/50130875/391326796-a09cd245-ca5f-445a-a40e-4f44bfb9d195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzY2MzEsIm5iZiI6MTczMzA3NjMzMSwicGF0aCI6Ii81MDEzMDg3NS8zOTEzMjY3OTYtYTA5Y2QyNDUtY2E1Zi00NDVhLWE0MGUtNGY0NGJmYjlkMTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDVkYzQ3NTkzOTQ3MGEyODEyMmEwZjRlN2U3ODE3ZDg1NWEwYWVkMDhiOGM0NTg5MGQ0OGU3Y2I4NDQ1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PMQm2Z7yqFEWE9wNZjggdNaun7myHHnUM9ZRDHnx_Mw) ![image](https://private-user-images.githubusercontent.com/50130875/391326890-91af728d-90c1-4916-a503-27ab02a5441b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzY2MzEsIm5iZiI6MTczMzA3NjMzMSwicGF0aCI6Ii81MDEzMDg3NS8zOTEzMjY4OTAtOTFhZjcyOGQtOTBjMS00OTE2LWE1MDMtMjdhYjAyYTU0NDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZmQ2MGYxYTJkNTgzMjg1MjFlNWQ1ODg3MDMwOGI0MDVmODg4M2ZlMWJiNjhlNzM2YTdkZmMzNjRmMzRmNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-eLBTSG0N0DDbt_tDvftDhgkzGiniavjAgEF6ZMEpac) ![image](https://private-user-images.githubusercontent.com/50130875/391326910-9628f331-33f0-452f-8634-a1a94a2916a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzY2MzEsIm5iZiI6MTczMzA3NjMzMSwicGF0aCI6Ii81MDEzMDg3NS8zOTEzMjY5MTAtOTYyOGYzMzEtMzNmMC00NTJmLTg2MzQtYTFhOTRhMjkxNmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZDljYTdjOThiZmQ2YWY2NzAwYTQ5MTY0MDQwNjIxZWE0ZWJkMDc0YTRiZjU4ZDJhZjgzMzZhYzBlMjhmYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wWmx3T2S1BNIhvLSJExpzrU2ClQrWpMkyBxa525kmO8)
> 
> ![image](https://private-user-images.githubusercontent.com/50130875/391327033-2afa30f0-52ef-4207-9eeb-70a53044162e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzY2MzEsIm5iZiI6MTczMzA3NjMzMSwicGF0aCI6Ii81MDEzMDg3NS8zOTEzMjcwMzMtMmFmYTMwZjAtNTJlZi00MjA3LTllZWItNzBhNTMwNDQxNjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjNhMWQ1MzY3ZTk3Y2UwMGI4NzdhYWQ2OTZlYWI4NDYwOGE0MjkwYzM2ZDE2YWQ4MTdmMjEwYjQ5NGIxYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0NTcKzDHWj2sBYrz7MXiJZ1Eul3mg_obPypQMDt4ZgU) 此处为解压消息体，不可以移除

好的谢谢提醒，下面是我测试的结果：
#### 结论：
1. 当设置超时时间都为60秒时，第一次调用函数时间过长，后续调用没有问题。
2. 当设置超时时间都为30秒时，代码持续报timeout
#### 第一种情况
![image](https://github.com/user-attachments/assets/9724baa2-c72d-43bb-aa15-428f2bf465a1)
![image](https://github.com/user-attachments/assets/5c02fa05-9478-4c8b-abfa-6d28058476d4)
#### 第二种情况
![image](https://github.com/user-attachments/assets/b2440fa6-991e-43a4-b117-bbdaa5a99d0e)
![image](https://github.com/user-attachments/assets/37ed989d-e6f8-4cd6-8773-849052fa3b79)

**Comment by AsQuantum** [comment]
> > > 请使用Okhttp3中的Response.receivedResponseAtMillis() - Response.sentRequestAtMillis()来获取具体的网络响应时间，并确保你的okhttp3的版本为 4.12.0 ![image](https://private-user-images.githubusercontent.com/50130875/391326796-a09cd245-ca5f-445a-a40e-4f44bfb9d195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzY2MzEsIm5iZiI6MTczMzA3NjMzMSwicGF0aCI6Ii81MDEzMDg3NS8zOTEzMjY3OTYtYTA5Y2QyNDUtY2E1Zi00NDVhLWE0MGUtNGY0NGJmYjlkMTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDVkYzQ3NTkzOTQ3MGEyODEyMmEwZjRlN2U3ODE3ZDg1NWEwYWVkMDhiOGM0NTg5MGQ0OGU3Y2I4NDQ1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PMQm2Z7yqFEWE9wNZjggdNaun7myHHnUM9ZRDHnx_Mw) ![image](https://private-user-images.githubusercontent.com/50130875/391326890-91af728d-90c1-4916-a503-27ab02a5441b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzY2MzEsIm5iZiI6MTczMzA3NjMzMSwicGF0aCI6Ii81MDEzMDg3NS8zOTEzMjY4OTAtOTFhZjcyOGQtOTBjMS00OTE2LWE1MDMtMjdhYjAyYTU0NDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZmQ2MGYxYTJkNTgzMjg1MjFlNWQ1ODg3MDMwOGI0MDVmODg4M2ZlMWJiNjhlNzM2YTdkZmMzNjRmMzRmNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-eLBTSG0N0DDbt_tDvftDhgkzGiniavjAgEF6ZMEpac) ![image](https://private-user-images.githubusercontent.com/50130875/391326910-9628f331-33f0-452f-8634-a1a94a2916a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzY2MzEsIm5iZiI6MTczMzA3NjMzMSwicGF0aCI6Ii81MDEzMDg3NS8zOTEzMjY5MTAtOTYyOGYzMzEtMzNmMC00NTJmLTg2MzQtYTFhOTRhMjkxNmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZDljYTdjOThiZmQ2YWY2NzAwYTQ5MTY0MDQwNjIxZWE0ZWJkMDc0YTRiZjU4ZDJhZjgzMzZhYzBlMjhmYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wWmx3T2S1BNIhvLSJExpzrU2ClQrWpMkyBxa525kmO8)
> > > ![image](https://private-user-images.githubusercontent.com/50130875/391327033-2afa30f0-52ef-4207-9eeb-70a53044162e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzY2MzEsIm5iZiI6MTczMzA3NjMzMSwicGF0aCI6Ii81MDEzMDg3NS8zOTEzMjcwMzMtMmFmYTMwZjAtNTJlZi00MjA3LTllZWItNzBhNTMwNDQxNjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjNhMWQ1MzY3ZTk3Y2UwMGI4NzdhYWQ2OTZlYWI4NDYwOGE0MjkwYzM2ZDE2YWQ4MTdmMjEwYjQ5NGIxYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0NTcKzDHWj2sBYrz7MXiJZ1Eul3mg_obPypQMDt4ZgU) 此处为解压消息体，不可以移除
> > 
> > 
> > 好的谢谢提醒，下面是我测试的结果：
> > #### 结论：
> > 
> > 1. 当设置超时时间都为60秒时，第一次调用函数时间过长，后续调用没有问题。
> > 2. 当设置超时时间都为30秒时，代码持续报timeout
> >    ![image](https://private-user-images.githubusercontent.com/100147969/391354108-e94f1c74-574b-4eda-935b-2442613678b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzgyMTksIm5iZiI6MTczMzA3NzkxOSwicGF0aCI6Ii8xMDAxNDc5NjkvMzkxMzU0MTA4LWU5NGYxYzc0LTU3NGItNGVkYS05MzViLTI0NDI2MTM2NzhiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxODMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGI3ZDEyOWEwODU4NjA4OGUwMjkxZTRjNjZlYzhjNDI1ZGQ1MjliM2M2ZTc1NDAzZWY3MDMyYzgxYmQ2MGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.__5nK-f-OaSuJtwPZYSggUkCjpeOA2skD77c8_bvAds)
> > 
> > #### 第一种情况
> > ![image](https://private-user-images.githubusercontent.com/100147969/391353249-9724baa2-c72d-43bb-aa15-428f2bf465a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzgyMTksIm5iZiI6MTczMzA3NzkxOSwicGF0aCI6Ii8xMDAxNDc5NjkvMzkxMzUzMjQ5LTk3MjRiYWEyLWM3MmQtNDNiYi1hYTE1LTQyOGYyYmY0NjVhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxODMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2NiOTFhNjQ1ZTUwNjYzNzdmYzMwYTQyMGRkNGIxYmEzMThiY2E3YjA2OWM4YTVjZWY3MzJlMjMwMTUzNjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Dt9O1D0Y6hHitzrOlr7cGRbjeTxTFBCkROMQwBryCwQ) ![image](https://private-user-images.githubusercontent.com/100147969/391353354-5c02fa05-9478-4c8b-abfa-6d28058476d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzgyMTksIm5iZiI6MTczMzA3NzkxOSwicGF0aCI6Ii8xMDAxNDc5NjkvMzkxMzUzMzU0LTVjMDJmYTA1LTk0NzgtNGM4Yi1hYmZhLTZkMjgwNTg0NzZkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxODMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmY0Y2I1M2YxYjZlMjI0NzQ2NjdhOTM2NWY1ZTQyOTg5YmFlNDdkMTM1NzI1MmVlNDkxODFjOTIxYTA4MzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T4c1C7uyrwvsTY1rjISig5uSvfrthduwIdVFbtqdCRI)
> > #### 第二种情况
> > ![image](https://private-user-images.githubusercontent.com/100147969/391353388-b2440fa6-991e-43a4-b117-bbdaa5a99d0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzgyMTksIm5iZiI6MTczMzA3NzkxOSwicGF0aCI6Ii8xMDAxNDc5NjkvMzkxMzUzMzg4LWIyNDQwZmE2LTk5MWUtNDNhNC1iMTE3LWJiZGFhNWE5OWQwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxODMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2U5OTU4MWFmNjBiZmUxMmZmNjlhMWEyMjU3MjY1NjRmYjE2MDViOGU4ODc0ZGE3ZjhkZWZjNWY3YjJlYTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3DgmxnjU9zFgL2I20baGwHNlxF2mXp3RblV13omsDEY) ![image](https://private-user-images.githubusercontent.com/100147969/391353549-37ed989d-e6f8-4cd6-8773-849052fa3b79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzgyMTksIm5iZiI6MTczMzA3NzkxOSwicGF0aCI6Ii8xMDAxNDc5NjkvMzkxMzUzNTQ5LTM3ZWQ5ODlkLWU2ZjgtNGNkNi04NzczLTg0OTA1MmZhM2I3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxODMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTRiOTQ0ZWFlMmUxMWZjYjU3NTRhNmQ4NzUzZmNiMzViYjhjODk3YzBkNWFjMjMwYmIxNTJlMzdlZjEwMWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uO8INkDpWZjS3ralxpH3MTUaEWqJRPl0def6NoEUUes)
> 
> 请拉取最新代码，使用TestHttpUtils进行测试 ![image](https://private-user-images.githubusercontent.com/50130875/391355436-f65f97c7-129b-4068-a5c0-09f7f9494595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTE5MjcsIm5iZiI6MTczMzExMTYyNywicGF0aCI6Ii81MDEzMDg3NS8zOTEzNTU0MzYtZjY1Zjk3YzctMTI5Yi00MDY4LWE1YzAtMDlmN2Y5NDk0NTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAzNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNGNiZWRkODE4ZjgzNDk5MWEyNTI0NWQxMDAzMGQyOWJkMzU4M2Q0NjkzY2FhNDQ0NGVjZDA2NmNmZjA0YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VK2ZmcsX6uGhrKE_BGMDEQwWAHuprkXYhc8-i97zLlg)
你好测试结果是一样的：
#### 当前代码执行结果：
![image](https://github.com/user-attachments/assets/7ecaeba3-09a8-40ae-9dd0-45066099af53)
![image](https://github.com/user-attachments/assets/9428e8a6-1c06-4a82-b050-9fc61d2ed8f0)
#### 修改callTimeOut为60后结果：
![image](https://github.com/user-attachments/assets/6bfbdb43-247e-460f-bbc1-8dc29b5d266c)
![image](https://github.com/user-attachments/assets/b7818c4b-946b-4980-850a-34a4dd29885f)

**Comment by KingPrimes** [comment]
我将调用超时更改到了60s，你到 https://github.com/KingPrimes/NyxBot/actions/runs/12119662009 下载测试构建查看一下问题是否得到解决？

**Comment by AsQuantum** [comment]
> 我将调用超时更改到了60s，你到 https://github.com/KingPrimes/NyxBot/actions/runs/12119662009 下载测试构建查看一下问题是否得到解决？

已解决，感谢。
